#!/bin/bash
set -ev

if [[ -n "$PULSE_COOKIE_DATA" ]]; then
    echo -ne $(echo $PULSE_COOKIE_DATA | sed -e 's/../\\x&/g') >$HOME/pulse.cookie
    export PULSE_COOKIE=$HOME/pulse.cookie
fi

case "$1" in
	*)
		exec "$@"
		;;
esac
