#!/bin/bash
set -eo pipefail

file="${1##*/}"
case "${file,,}" in
	*compose*)        file=docker-compose.yml ;;
	*readme*|*help*)  file=README.md ;;
esac
absfile="$APP_ROOT/host/$file"

case "${file,,}" in
	run)
		mopidy_args=("${@:2}")
		content=(
			'#!/bin/bash\n'
			'main() {\n'
			"	$(declare -p mopidy_args | sed -e 's/^declare/local/')\n"
			'	set -- "$@" "${mopidy_args[@]}"\n'
			"	$(< "$absfile")\n"
			'}\n'
			'main "$@"\n'
		)

		echo "${content[@]}"
		exit 0
		;;
esac

if [[ ! -f "$absfile" ]]; then
	echo "File $absfile not found." >&2
	exit 1
fi

exec cat "$absfile"
