#!/bin/bash
set -eo pipefail
. "$IMAGE_ROOT/lib.sh"

for xdg_k_dir in "${!XDG_@_DIR}"; do
    xdg_k_home="${xdg_k_dir%_DIR}_HOME"
    declare -n xdg_v_dir="$xdg_k_dir" xdg_v_home="$xdg_k_home"
    : ${xdg_v_dir:="$xdg_v_home"}
done

if [[ $UID -eq 0 && -z "$_SENTINEL" ]]; then
	(
		exec >&2
    	userdel "$APP_USER" >/dev/null 2>&1 || :
		useradd -U -G audio -d "$APP_ROOT" -s /bin/bash -M -o -u "$APP_UID" "$APP_USER"
    	mkdir -pv {"$XDG_CONFIG_DIR","$XDG_DATA_DIR"}/mopidy
    	chown -c "$APP_USER" "$APP_ROOT" {"$XDG_CONFIG_DIR","$XDG_DATA_DIR"}{,/mopidy}
    )

    debug "Delevating privileges to $APP_USER($APP_UID)"
    export ${!*} _SENTINEL=true
    exec gosu "$APP_USER" "$0" "$@"
fi

debug "Running as: $(id -un)"

if [[ ! -f "$XDG_CONFIG_DIR/mopidy/mopidy.conf" ]]; then
    cp -av "$APP_ROOT/image/mopidy.conf" "$XDG_CONFIG_DIR/mopidy/mopidy.conf" >&2
fi

if [[ -n "$PULSE_COOKIE_DATA" ]]; then
    : ${PULSE_COOKIE:="$HOME/pulse.cookie"}
    echo -ne $(echo $PULSE_COOKIE_DATA | sed -e 's/../\\x&/g') >"$PULSE_COOKIE"
fi

debug_call exec "${0##*/}" "$@"
