#!/bin/bash
set -eo pipefail
set -xv

PATH="$PWD/circle:$PATH"

if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
    echo "Running for a PR? Nope." >&2
    exit 403
fi

build_image="$DOCKER_USER/$CIRCLE_PROJECT_REPONAME:build-$CIRCLE_BUILD_NUM"
push_repo="$DOCKER_USER/${DOCKER_REPONAME:-$CIRCLE_PROJECT_REPONAME}"

case "$CIRCLE_BRANCH" in
    master)
        tags=(latest)
        ;;
    develop)
        tags=($CIRCLE_BRANCH)
        ;;
esac

echo "build_image=$build_image"
echo "push_repo=$push_repo"
echo "tags:"
for tag in "${tags[@]}"; do
    echo "- $tag"
done

case "$1" in
    build)
        docker build -t "$build_image" .
        ;;
    test)
        #docker run "$build_image" integration-tests
        :
        ;;
    push)
        docker-login
        for tag in "${tags[@]}"; do
            docker tag "$build_image" "$push_repo:$tag"
            docker push "$push_repo:$tag"
        done
        ;;
    *)
        echo "Unknown build step $1" >&2
        exit 1
esac

