#!/bin/bash
set -e

case "$1" in
	host)
		file=$(basename "$2")
		case "${file,,}" in
			*compose*)        file=docker-compose.yml ;;
			*readme*|*help*)  file=README.md ;;
		esac
		absfile="$APP_HOME/host/$file"

		case "${file,,}" in
			run)
				absfile=run
				echo -e "#!/bin/bash\nmain() {\n"
				cat "$absfile"
				echo -e "\n}\nmain" "$@" '"$@"'
				exit 0
				;;
		esac

		if [[ ! -f "$absfile" ]]; then
			echo "File $absfile not found." >&2
			exit 1
		fi

		exec cat "$absfile"
		;;
	-*)
		# If we're just given options, prefix mopidy
		set -- mopidy "$@"
		;;
esac

if [[ $UID -eq 0 && -z "$_SENTINEL" ]]; then
    mkdir -pv {"$XDG_CONFIG_HOME","$XDG_DATA_HOME"}/mopidy
    chown -c "$APP_USER" {"$XDG_CONFIG_HOME","$XDG_DATA_HOME"}{,/mopidy}

    export ${!*} _SENTINEL=true
    exec gosu "$APP_USER" "$0" "$@"
fi

if [[ ! -f "$XDG_CONFIG_HOME/mopidy/mopidy.conf" ]]; then
    cp -av "$APP_HOME/image/mopidy.conf" "$XDG_CONFIG_HOME/mopidy/mopidy.conf" >&2
fi

if [[ -n "$PULSE_COOKIE_DATA" ]]; then
    : ${PULSE_COOKIE:="$HOME/pulse.cookie"}
    echo -ne $(echo $PULSE_COOKIE_DATA | sed -e 's/../\\x&/g') >"$PULSE_COOKIE"
fi

exec "$@"
